fn main() -> Result<(), std::fmt::Error> {
    Ok(())
}
